AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: goreleaser-aws-lambda-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Parameters:
  AppVersion:
    Type: String
    Default: latest  
  AppName:
    Type: String
    Default: app-name
  AppReleaseS3FilePath:
    Type: String
    Default: example.zip

Resources:
  GoReleaserExampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: !Ref AppReleaseS3FilePath
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_VERSION: !Ref AppVersion
          APP_NAME: !Ref AppName
          APP_RELEASE: !Ref AppReleaseS3FilePath

Outputs:
  GoReleaserExampleFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt GoReleaserExampleFunction.Arn
  GoReleaserExampleFunctionIamRole:
    Description: "Implicit IAM Role created for GoReleaserExampleFunction"
    Value: !GetAtt GoReleaserExampleFunctionRole.Arn
