name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'
    # Triggers the workflow on push or pull request events but only for the "main" branch
    branches:
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Setup Golang env
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true

      - name: List dependencies and updated versions
        run: go list -m -u all

      - name: Prune unused dependencies, include dependencies for all possible OS/architectures
        run: go mod tidy

      - name: Verify dependencies with their hashes
        run: go mod verify

      - name: Run Go analyzers in the current and all sub-directories
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run tests
        run: go test -race -vet=off ./...

      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
