name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'
    # Triggers the workflow on push or pull request events but only for the "main" branch
    branches:
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# These permissions are needed for the job to interact with GitHub's OIDC Token endpoint.
permissions:
  contents: write  
  id-token: write
  # packages: write
  # issues: write

env:
  SAM_CLI_TELEMETRY: 0

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Setup Golang env
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true

      - name: List dependencies and updated versions
        run: go list -m -u all

      - name: Prune unused dependencies, include dependencies for all possible OS/architectures
        run: go mod tidy

      - name: Verify dependencies with their hashes
        run: go mod verify

      - name: Run Go analyzers in the current and all sub-directories
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run tests
        run: go test -race -vet=off ./...

      - name: Retreive GitHub Repo name
        env:
          GITHUB_REPO: ${{ github.repository }}
        id: split
        run: echo "::set-output name=fragment::${GITHUB_REPO##*/}"

      - name: GITHUB_REPO
        run: |
          echo ${{ steps.split.outputs.fragment }}

      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}

      - name: List Build artifacts
        run: ls -alrt ./dist

      - name: Setup Python for SAM CLI
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.8"

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::703730886047:role/github-actions-georgedavis-triumphtech

      - name: Validate SAM template
        run: sam validate --lint

      - name: SAM Build
        run: sam build # --use-container

      - name: SAM Deploy
        run: "sam deploy --config-env default --parameter-overrides ParameterKey=AppVersion,ParameterValue=${{ github.ref_name }}-${{ github.run_attempt }} ParameterKey=AppName,ParameterValue=${{ steps.split.outputs.fragment }} --no-confirm-changeset --no-fail-on-empty-changeset"
